package de.konradvoelkel.android.autokorrektur.pipeline

import android.content.Context
import android.graphics.Bitmap
import android.net.Uri
import de.konradvoelkel.android.autokorrektur.ml.ImagePreprocessingService
import de.konradvoelkel.android.autokorrektur.ml.ImageProcessor
import de.konradvoelkel.android.autokorrektur.ml.InpaintingEngine
import de.konradvoelkel.android.autokorrektur.ml.MiGanInference
import de.konradvoelkel.android.autokorrektur.ml.api.ServerInpainter
import de.konradvoelkel.android.autokorrektur.ml.api.YoloService
import de.konradvoelkel.android.autokorrektur.ml.api.YoloServiceImpl
import de.konradvoelkel.android.autokorrektur.ml.engine.YoloTFLiteEngine
import de.konradvoelkel.android.autokorrektur.ml.config.YoloConfig
import de.konradvoelkel.android.autokorrektur.ml.progressive.ProgressiveTileInpainter
import de.konradvoelkel.android.autokorrektur.model.InpaintingQualityMode
import de.konradvoelkel.android.autokorrektur.telemetry.Telemetry
import de.konradvoelkel.android.autokorrektur.utils.AppLogger
import de.konradvoelkel.android.autokorrektur.utils.DevicePerformanceHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.withContext
import org.opencv.android.Utils
import org.opencv.core.Mat
import androidx.core.graphics.createBitmap
import de.konradvoelkel.android.autokorrektur.ml.MatScaler
import de.konradvoelkel.android.autokorrektur.ml.api.ServerSdxlApi

/**
 * Represents the final result of the image processing pipeline.
 *
 * @property originalBitmap The original source image as loaded.
 * @property maskBitmap The binary segmentation mask generated by YOLO.
 * @property inpaintedBitmap The final car-free result (null if processing failed).
 * @property isServerProcessed True if the high-quality SDXL backend was used.
 * @property errorMessage Error description if the pipeline failed.
 */
data class PipelineResult(
    val originalBitmap: Bitmap,
    val maskBitmap: Bitmap,
    val inpaintedBitmap: Bitmap?,
    val isServerProcessed: Boolean = false,
    val errorMessage: String? = null
)

/**
 * Orchestrates the full image processing workflow:
 * 1. Image loading and preprocessing (via [ImageProcessor])
 * 2. Object detection and mask generation (via [YoloService])
 * 3. Neural inpainting (via [InpaintingEngine], [ProgressiveTileInpainter], or [ServerSdxlApi])
 */
class StaticImagePipeline(
    private val imageProcessor: ImagePreprocessingService,
    private val yoloService: YoloService,
    private val miGanInference: InpaintingEngine,
    private val serverSdxlApi: ServerInpainter
) {
    /**
     * True if the underlying YOLO neural engine has been initialized and is ready for inference.
     */
    val isInitialized: Boolean
        get() = yoloService.isInitialized
    
    /**
     * Initializes the YOLO model weights and the on-device MI-GAN inpainting session.
     */
    suspend fun initialize() = withContext(Dispatchers.Default) {
        val modelName = "yolo11s"
        AppLogger.info("StaticImagePipeline initializing with model: $modelName")

        yoloService.initialize(modelName = modelName)
        miGanInference.initialize()
    }

    /**
     * Runs the complete pipeline on a single image URI:
     * loads image, runs YOLO segmentation, and performs inpainting.
     *
     * @param uri URI of the input image
     * @param downscaleMp Optional downscale limit in megapixels
     * @param maskUpscale Scale factor for mask boundary dilation
     * @param scoreThreshold Confidence threshold for vehicle detection
     * @param useServerSdxl True to use remote SDXL, false for on-device MI-GAN
     * @param qualityMode Inpainting computation and resolution mode
     * @param onMaskGenerated Optional callback receiving the intermediate mask Bitmap
     * @param onProgressUpdate Optional progress reporter callback (localizable [PipelineStage], percent)
     * @param onIntermediateInpaintUpdate Optional callback for progressive inpainting preview updates
     */
    suspend fun processImage(
        uri: Uri,
        downscaleMp: Float?,
        maskUpscale: Float,
        scoreThreshold: Float,
        useServerSdxl: Boolean = false,
        qualityMode: InpaintingQualityMode = if (useServerSdxl) InpaintingQualityMode.CLOUD_SDXL else InpaintingQualityMode.FAST_PREVIEW,
        onMaskGenerated: ((Bitmap) -> Unit)? = null,
        onProgressUpdate: ((stage: PipelineStage, percent: Int) -> Unit)? = null,
        onIntermediateInpaintUpdate: ((Bitmap) -> Unit)? = null
    ): PipelineResult = withContext(Dispatchers.Default) {
        if (!isInitialized) {
            AppLogger.info("StaticImagePipeline processImage called on uninitialized pipeline; auto-initializing now...")
            onProgressUpdate?.invoke(PipelineStage.INITIALIZING_ENGINES, 10)
            initialize()
        }

        var processedImage: ImageProcessor.ProcessedImage? = null
        var maskMat: Mat? = null
        // Diagnostics (opt-in, PRIVACY_POLICY.md §6): stage timings, pixel counts, detection
        // count and the outcome. Primitives only — never the image, the URI or an error message.
        val runStartNs = System.nanoTime()
        var preprocessMs = -1L
        var segmentationMs = -1L
        var inpaintMs = -1L
        var detectionCount = -1
        var inputPixels = -1L
        val effectiveMode = if (useServerSdxl) InpaintingQualityMode.CLOUD_SDXL else qualityMode
        try {
            currentCoroutineContext().ensureActive()

            // 1. Process Input
            onProgressUpdate?.invoke(PipelineStage.LOADING_IMAGE, 25)
            var stageStartNs = System.nanoTime()
            val effectiveDownscaleMp = if (qualityMode == InpaintingQualityMode.HIGH_RES_PROGRESSIVE) null else downscaleMp
            processedImage = imageProcessor.processInputImage(
                imageUri = uri,
                modelWidth = 640,
                modelHeight = 640,
                downscaleMp = effectiveDownscaleMp
            )
            preprocessMs = (System.nanoTime() - stageStartNs) / 1_000_000
            inputPixels = processedImage.originalMat.cols().toLong() * processedImage.originalMat.rows()
            
            currentCoroutineContext().ensureActive()

            // 2. YOLO Mask Generation
            onProgressUpdate?.invoke(PipelineStage.SEGMENTATION, 50)
            stageStartNs = System.nanoTime()
            val config = YoloConfig(scoreThreshold = scoreThreshold)
            val yoloResult = yoloService.inferDetailed(
                transformedMat = processedImage.transformedMat,
                xRatio = processedImage.xRatio,
                yRatio = processedImage.yRatio,
                upscaleFactor = maskUpscale,
                originalWidth = processedImage.originalMat.cols(),
                originalHeight = processedImage.originalMat.rows(),
                overrideConfig = config
            )
            maskMat = yoloResult.mask
            segmentationMs = (System.nanoTime() - stageStartNs) / 1_000_000
            detectionCount = yoloResult.detections.size
            
            // Generate Mask Bitmap for UI
            val maskBitmap = Bitmap.createBitmap(
                maskMat.cols(),
                maskMat.rows(),
                Bitmap.Config.ARGB_8888
            )
            Utils.matToBitmap(maskMat, maskBitmap)
            onMaskGenerated?.invoke(maskBitmap)

            currentCoroutineContext().ensureActive()

            // 3. Neural Inpainting based on Quality Mode
            val isServer = (qualityMode == InpaintingQualityMode.CLOUD_SDXL) || useServerSdxl
            stageStartNs = System.nanoTime()
            val inpaintedBitmap = when {
                isServer -> {
                    onProgressUpdate?.invoke(PipelineStage.INPAINTING_CLOUD, 75)
                    serverSdxlApi.processWithSdxl(
                        originalBitmap = processedImage.originalBitmap,
                        maskBitmap = maskBitmap,
                        previewBitmap = processedImage.transformedBitmap
                    )
                }
                qualityMode == InpaintingQualityMode.HIGH_RES_PROGRESSIVE -> {
                    onProgressUpdate?.invoke(PipelineStage.INPAINTING_HIGH_RES, 60)
                    val progressiveInpainter = ProgressiveTileInpainter(miGanInference)
                    val inpaintMat = progressiveInpainter.inpaintProgressive(
                        fullImageMat = processedImage.originalMat,
                        subtractiveMaskMat = maskMat,
                        onProgress = { stage, percent, previewBmp ->
                            onProgressUpdate?.invoke(stage, percent)
                            if (previewBmp != null) {
                                onIntermediateInpaintUpdate?.invoke(previewBmp)
                            }
                        }
                    )
                    val outBmp = MatScaler.createDisplayBitmap(inpaintMat)
                    inpaintMat.release()
                    outBmp
                }
                else -> {
                    onProgressUpdate?.invoke(PipelineStage.INPAINTING_ON_DEVICE, 75)
                    val inpaintMat = miGanInference.inpaint(
                        imageMat = processedImage.originalMat,
                        maskMat = maskMat
                    )
                    val outBmp = MatScaler.createDisplayBitmap(inpaintMat)
                    inpaintMat.release()
                    outBmp
                }
            }
            
            inpaintMs = (System.nanoTime() - stageStartNs) / 1_000_000
            
            currentCoroutineContext().ensureActive()

            recordRun(effectiveMode, runStartNs, preprocessMs, segmentationMs, inpaintMs, inputPixels, detectionCount, downscaleMp, error = null)
            onProgressUpdate?.invoke(PipelineStage.COMPLETED, 100)
            return@withContext PipelineResult(
                originalBitmap = processedImage.originalBitmap,
                maskBitmap = maskBitmap,
                inpaintedBitmap = inpaintedBitmap,
                isServerProcessed = isServer
            )
            
        } catch (e: Exception) {
            if (e is kotlinx.coroutines.CancellationException) throw e
            AppLogger.error("StaticImagePipeline Error", e)
            recordRun(effectiveMode, runStartNs, preprocessMs, segmentationMs, inpaintMs, inputPixels, detectionCount, downscaleMp, error = e)
            return@withContext PipelineResult(
                originalBitmap = processedImage?.originalBitmap ?: createBitmap(1, 1),
                maskBitmap = createBitmap(1, 1),
                inpaintedBitmap = null,
                errorMessage = e.message
            )
        } finally {
            processedImage?.transformedBitmap?.recycle()
            processedImage?.release()
            maskMat?.release()
        }
    }

    fun close() {
        yoloService.close()
        miGanInference.close()
    }

    /** One `pipeline_run` diagnostics line; -1 marks a stage that was never reached. */
    private fun recordRun(
        mode: InpaintingQualityMode,
        runStartNs: Long,
        preprocessMs: Long,
        segmentationMs: Long,
        inpaintMs: Long,
        inputPixels: Long,
        detectionCount: Int,
        downscaleMp: Float?,
        error: Exception?
    ) {
        Telemetry.record(
            "pipeline_run",
            mapOf(
                "mode" to mode.name,
                "total_ms" to (System.nanoTime() - runStartNs) / 1_000_000,
                "preprocess_ms" to preprocessMs,
                "segmentation_ms" to segmentationMs,
                "inpaint_ms" to inpaintMs,
                "input_pixels" to inputPixels,
                "downscale_mp" to downscaleMp,
                "detections" to detectionCount,
                "success" to (error == null),
                "error" to error?.javaClass?.simpleName,
            )
        )
    }

    companion object {
        /**
         * Factory function to create a fully wired [StaticImagePipeline] with production dependencies.
         */
        fun create(context: Context): StaticImagePipeline {
            val imageProcessor = ImageProcessor(context)
            val yoloService = YoloServiceImpl(YoloTFLiteEngine(context))
            val inpaintingEngine = MiGanInference(context)
            val serverSdxlApi = ServerSdxlApi(context)
            return StaticImagePipeline(
                imageProcessor = imageProcessor,
                yoloService = yoloService,
                miGanInference = inpaintingEngine,
                serverSdxlApi = serverSdxlApi
            )
        }
    }
}
