package de.konradvoelkel.android.autokorrektur.pipeline

import android.content.Context
import android.graphics.Bitmap
import android.net.Uri
import de.konradvoelkel.android.autokorrektur.ml.ImagePreprocessingService
import de.konradvoelkel.android.autokorrektur.ml.ImageProcessor
import de.konradvoelkel.android.autokorrektur.ml.InpaintingEngine
import de.konradvoelkel.android.autokorrektur.ml.MiGanInference
import de.konradvoelkel.android.autokorrektur.ml.api.ServerInpainter
import de.konradvoelkel.android.autokorrektur.ml.api.YoloService
import de.konradvoelkel.android.autokorrektur.ml.api.YoloServiceImpl
import de.konradvoelkel.android.autokorrektur.ml.config.YoloConfig
import de.konradvoelkel.android.autokorrektur.utils.AppLogger
import de.konradvoelkel.android.autokorrektur.utils.DevicePerformanceHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.opencv.android.Utils
import org.opencv.core.Mat
import androidx.core.graphics.createBitmap
import de.konradvoelkel.android.autokorrektur.ml.MatScaler
import de.konradvoelkel.android.autokorrektur.ml.api.ServerSdxlApi

/**
 * Represents the final result of the image processing pipeline.
 *
 * @property originalBitmap The original source image as loaded.
 * @property maskBitmap The binary segmentation mask generated by YOLO.
 * @property inpaintedBitmap The final car-free result (null if processing failed).
 * @property isServerProcessed True if the high-quality SDXL backend was used.
 * @property errorMessage Error description if the pipeline failed.
 */
data class PipelineResult(
    val originalBitmap: Bitmap,
    val maskBitmap: Bitmap,
    val inpaintedBitmap: Bitmap?,
    val isServerProcessed: Boolean = false,
    val errorMessage: String? = null
)

/**
 * Orchestrates the full image processing workflow:
 * 1. Image loading and preprocessing (via [ImageProcessor])
 * 2. Object detection and mask generation (via [YoloService])
 * 3. Neural inpainting (via [InpaintingEngine] or [ServerSdxlApi])
 */
class StaticImagePipeline(
    private val imageProcessor: ImagePreprocessingService,
    private val yoloService: YoloService,
    private val miGanInference: InpaintingEngine,
    private val serverSdxlApi: ServerInpainter
) {
    val isInitialized: Boolean
        get() = yoloService.isInitialized
    
    suspend fun initialize() = withContext(Dispatchers.Default) {
        val modelName = "yolo11s"
        AppLogger.info("StaticImagePipeline initializing with model: $modelName")

        yoloService.initialize(modelName = modelName, useFP16 = false)
        miGanInference.initialize()
    }

    suspend fun processImage(
        uri: Uri,
        downscaleMp: Float?,
        maskUpscale: Float,
        scoreThreshold: Float,
        useServerSdxl: Boolean,
        onMaskGenerated: ((Bitmap) -> Unit)? = null,
        onProgressUpdate: ((stage: String, percent: Int) -> Unit)? = null
    ): PipelineResult = withContext(Dispatchers.Default) {
        if (!isInitialized) {
            AppLogger.info("StaticImagePipeline processImage called on uninitialized pipeline; auto-initializing now...")
            onProgressUpdate?.invoke("Initializing Neural Engines", 10)
            initialize()
        }

        var processedImage: ImageProcessor.ProcessedImage? = null
        var maskMat: Mat? = null
        try {
            // 1. Process Input
            onProgressUpdate?.invoke("Loading & Preprocessing Image", 25)
            processedImage = imageProcessor.processInputImage(
                imageUri = uri,
                modelWidth = 640,
                modelHeight = 640,
                downscaleMp = downscaleMp
            )
            
            // 2. YOLO Mask Generation
            onProgressUpdate?.invoke("Running YOLO Segmentation", 50)
            val config = YoloConfig(scoreThreshold = scoreThreshold)
            val yoloResult = yoloService.inferDetailed(
                transformedMat = processedImage.transformedMat,
                xRatio = processedImage.xRatio,
                yRatio = processedImage.yRatio,
                upscaleFactor = maskUpscale,
                originalWidth = processedImage.originalMat.cols(),
                originalHeight = processedImage.originalMat.rows(),
                overrideConfig = config
            )
            val currentMaskMat = yoloResult.mask
            maskMat = currentMaskMat
            
            // Convert mask to Bitmap
            val maskBitmap = MatScaler.createDisplayBitmap(currentMaskMat)
            
            onMaskGenerated?.invoke(maskBitmap)

            // 3. Inpainting
            val inpaintedBitmap: Bitmap?
            if (useServerSdxl) {
                onProgressUpdate?.invoke("Generating Structural Prior (Mi-GAN)", 70)
                AppLogger.info("Using Server SDXL for inpainting")
                // Generate a preview with MiGan first to use as structural prior
                val miGanPreview =
                    miGanInference.inferMiGan(processedImage.originalMat, currentMaskMat)
                val previewBitmap = MatScaler.createDisplayBitmap(miGanPreview)
                miGanPreview.release()
                
                onProgressUpdate?.invoke("Server SDXL Premium Edit Processing", 85)
                // Send to server
                inpaintedBitmap = serverSdxlApi.processWithSdxl(processedImage.originalBitmap, maskBitmap, previewBitmap)
            } else {
                onProgressUpdate?.invoke("Running MI-GAN Neural Inpainting", 80)
                AppLogger.info("Using Local Mi-GAN for inpainting")
                val miGanResult =
                    miGanInference.inferMiGan(processedImage.originalMat, currentMaskMat)
                inpaintedBitmap = MatScaler.createDisplayBitmap(miGanResult)
                miGanResult.release()
            }
            
            onProgressUpdate?.invoke("Processing Complete", 100)
            return@withContext PipelineResult(
                originalBitmap = processedImage.originalBitmap,
                maskBitmap = maskBitmap,
                inpaintedBitmap = inpaintedBitmap,
                isServerProcessed = useServerSdxl
            )
            
        } catch (e: Exception) {
            AppLogger.error("StaticImagePipeline Error", e)
            return@withContext PipelineResult(
                originalBitmap = processedImage?.originalBitmap ?: createBitmap(1, 1),
                maskBitmap = createBitmap(1, 1),
                inpaintedBitmap = null,
                errorMessage = e.message
            )
        } finally {
            processedImage?.release()
            maskMat?.release()
        }
    }
    
    fun close() {
        yoloService.close()
        miGanInference.close()
    }
}
