#!/usr/bin/env bash
# Assembles the static tree for autokorrektur.org into OUT (default site/dist, gitignored):
#   /              site/index.html (de), en.html, impressum.html, site.css, robots.txt, icons/, img/
#   /privacy       privacy.html rendered by pandoc from PRIVACY_POLICY.md (German, the URL the Play
#                  listing points at) -- so the hosted policy cannot drift from the file
#   /privacy-en    privacy-en.html from PRIVACY_POLICY.en.md (minus its italic maintainers' note)
# Then precompresses text files (brotli if installed, zstd, gzip) for Caddy's `precompressed`.
# Same shape as Laberampel's site/build.sh, without the browser app and the APK downloads (the
# app is distributed through Google Play). Needs: pandoc, zstd, git. Deploying is site/deploy.sh.
# Nothing here touches the network.
set -euo pipefail
repo="$(cd "$(dirname "$0")/.." && pwd)"
out="${1:-$repo/site/dist}"
case "$out" in /*) ;; *) out="$PWD/$out" ;; esac

for tool in pandoc zstd git; do
  command -v "$tool" >/dev/null || { echo "build.sh: $tool not installed" >&2; exit 1; }
done
# versionName the way app/build.gradle.kts computes it (git describe --tags --always).
version=$(git -C "$repo" describe --tags --always 2>/dev/null || echo unknown)
built=$(git -C "$repo" log -1 --format=%cd --date=short 2>/dev/null || date -u +%Y-%m-%d)

rm -rf "$out"; mkdir -p "$out/icons" "$out/img"
cp -p "$repo"/site/{index.html,en.html,impressum.html,site.css,robots.txt} "$out/"
cp -p "$repo"/site/icons/* "$out/icons/"
cp -p "$repo/media/image_1_with_car_640x640.png" "$out/img/before.png"
cp -p "$repo/media/image_1_without_car_640x640.png" "$out/img/after.png"

# --- /privacy, /privacy-en from the two policy files ---------------------------------------------
# Drops an italic preamble (a paragraph in _..._ right after the title: repo notes, not policy text).
render_policy() { # <source .md> <output .html> <lang> <title> <home href> <nav html> <trailing note html>
  local src=$1 dst=$2 lang=$3 title=$4 home=$5 nav=$6 note=$7
  python3 - "$src" > "$dst.body.md" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
# The first paragraph that is entirely _italic_ (within the head of the file) is the repo note.
text = re.sub(r"(?ms)\A(.{0,400}?\n\n)_[^\n]*_\n\n", r"\1", text, count=1)
sys.stdout.write(text)
PY
  {
    cat <<HTML
<!DOCTYPE html>
<html lang="$lang">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<!-- Generated by site/build.sh from $(basename "$src"); edit that file, never this one. -->
<link rel="stylesheet" href="site.css">
<link rel="icon" href="icons/icon.svg" type="image/svg+xml">
</head>
<body>
<header class="site">
  <img src="icons/icon.svg" alt="" width="44" height="44">
  <a class="name" href="$home">AutoKorrektur</a>
  <nav>$nav</nav>
</header>
<main class="doc">
HTML
    pandoc -f gfm -t html5 "$dst.body.md"
    cat <<HTML
<p class="note">$note</p>
</main>
<footer class="site">$nav</footer>
</body>
</html>
HTML
  } > "$dst"
  rm "$dst.body.md"
}
render_policy "$repo/PRIVACY_POLICY.md" "$out/privacy.html" de "AutoKorrektur – Datenschutzerklärung" "./" \
  '<a href="./">Startseite</a><a href="impressum">Impressum</a><a href="privacy-en" lang="en" hreflang="en">English</a>' \
  "Gilt für die Android-App. Hosting dieser Website: <a href=\"impressum\">Impressum</a>. Text zum Stand von App-Version $version."
render_policy "$repo/PRIVACY_POLICY.en.md" "$out/privacy-en.html" en "AutoKorrektur – Privacy Policy" "en.html" \
  '<a href="en.html">Home</a><a href="impressum">Impressum</a><a href="privacy" lang="de" hreflang="de">Deutsch</a>' \
  "Applies to the Android app; the German <a href=\"privacy\" lang=\"de\">Datenschutzerklärung</a> is the binding text. Hosting of this website: <a href=\"impressum\">Impressum</a> (German). Text as of app version $version."

# --- placeholders ---------------------------------------------------------------------------------
for page in index.html en.html; do
  sed -i -e "s|__VERSION__|$version|g" -e "s|__DATE__|$built|g" "$out/$page"
  if grep -q '__[A-Z0-9_]*__' "$out/$page"; then echo "build.sh: unfilled placeholder in $page" >&2; exit 1; fi
done

# --- precompress (Caddy: file_server precompressed br zstd gzip) ---------------------------------
find "$out" -type f \( -name '*.html' -o -name '*.css' -o -name '*.svg' -o -name '*.txt' \) -print0 |
  xargs -0 -r -P "$(nproc)" -I{} sh -c '
    command -v brotli >/dev/null && brotli -kf "$1"
    zstd -q -kf -19 "$1"
    gzip -kf -9 "$1"' _ {}

echo "build.sh: $out -- version $version ($built), $(find "$out" -type f | wc -l) files, $(du -sh "$out" | cut -f1)"
